# Generated by Django 5.1.3 on 2024-11-12 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userddata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userddata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userddata',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='admins',
            field=models.ManyToManyField(related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupAccess',
        ),
        migrations.DeleteModel(
            name='userdData',
        ),
    ]
