# Generated by Django 5.1.3 on 2024-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_customuserdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserdata',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuserdata',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
