# Generated by Django 5.1.3 on 2024-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_device_created_at_device_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepassword',
            name='applytodevice',
            field=models.BooleanField(default=False),
        ),
    ]
