# Generated by Django 5.1.3 on 2024-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_alter_customuserdata_isadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdata',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
